name: Data Processing Pipeline

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  download-and-process-data:
    runs-on: ubuntu-latest
    timeout-minutes: 120

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Set up Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install docker-compose -y

      - name: Start Airflow with Docker Compose
        run: |
          docker-compose build --no-cache
          docker-compose up -d
          docker-compose ps

      - name: Wait for Airflow to start
        run: |
          until curl -s http://localhost:8080/health | grep -q '"healthy"}'; do
              echo "Waiting for Airflow components to be healthy..."
              curl -s http://localhost:8080/health || true
              sleep 5
          done

      - name: List all DAGs
        run: |
          docker-compose exec airflow airflow dags list
          docker-compose exec airflow airflow dags list-import-errors

      - name: Unpause retrieve_and_split_data DAG
        run: |
          docker-compose exec airflow airflow dags unpause retrieve_and_split_data

      - name: Unpause clean_and_standardize_data DAG
        run: |
          docker-compose exec airflow airflow dags unpause clean_and_standardize_data

      - name: Trigger retrieve_and_split_data DAG
        run: |
          docker-compose exec airflow airflow dags trigger retrieve_and_split_data

      - name: Trigger clean_and_standardize_data DAG
        run: |
          docker-compose exec airflow airflow dags trigger clean_and_standardize_data

      - name: Wait for retrieve_and_split_data DAG to finish
        run: |
          until [ "$(docker-compose exec airflow airflow dags list-runs -d retrieve_and_split_data | grep -E 'success|failed' | wc -l)" -gt 0 ]; do
              docker-compose exec airflow airflow dags list-runs -d retrieve_and_split_data
              docker-compose exec airflow airflow dags list-runs -d clean_and_standardize_data
              sleep 20
          done

      - name: Wait for clean_and_standardize_data DAG to finish
        run: |
          until [ "$(docker-compose exec airflow airflow dags list-runs -d clean_and_standardize_data | grep -E 'success|failed' | wc -l)" -gt 0 ]; do
              docker-compose exec airflow airflow dags list-runs -d retrieve_and_split_data
              docker-compose exec airflow airflow dags list-runs -d clean_and_standardize_data
              sleep 20
          done

      - name: Show retrieve_and_split_data DAG execution log
        run: |
          docker-compose exec airflow airflow dags list-runs -d retrieve_and_split_data

      - name: Show clean_and_standardize_data DAG execution log
        run: |
          docker-compose exec airflow airflow dags list-runs -d clean_and_standardize_data

      - name: Display Airflow Logs
        run: |
          docker-compose logs