name: Data Processing Pipeline

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  download-and-process-data:
    runs-on: ubuntu-latest
    timeout-minutes: 120  # Set the timeout to 120 minutes

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Download dataset
        run: |
          curl -L -o archive.zip https://www.kaggle.com/api/v1/datasets/download/bwandowando/tomtom-traffic-data-55-countries-387-cities
          unzip -o archive.zip -d dataset
          rm archive.zip

      - name: Run data processing script
        run: |
          python process_data.py